version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    container_name: "selenoid"
    volumes:
          - "./:/etc/selenoid/browsers.json"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "./video:/opt/selenoid/video"
          - "./logs:/opt/selenoid/logs"
          - "./config:/etc/selenoid"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/rr528091/video
      - TZ=Etc/UTC
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit 28"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    container_name: "selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri","http://amlnx-ldq-sln01.digital.prscoad.com:4444"]